### ISSUE TITLE
Cannot tap pinepain/devtools: invalid syntax in tap!

### ISSUE THREAD

**Issue by SoylentGraham** [pinepain/homebrew-devtools#5]
I'm trying to get a more up to date version of v8 (thanks btw!) but when I come to tap
`brew tap pinepain/devtools`
I get an error 
```
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pinepain/homebrew-devtools/Formula/php71-v8.rb
php71-v8: cannot load such file -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Abstract/abstract-php-extension
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pinepain/homebrew-devtools/Formula/php72-v8.rb
php72-v8: cannot load such file -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php-extension
Error: Cannot tap pinepain/devtools: invalid syntax in tap!
```
I guess this may be because of a dependency(?) on the php tap(formula?)
`brew tap homebrew/php`
gives
`Error: homebrew/php was deprecated. This tap is now empty as all its formulae were migrated.`

Is this an actual dependency, or have tap syntaxes changed? (I'm not familiar with protocol/syntaxes with the add-on taps of homebrew, just a user :)

On a side note, 
`brew install https://raw.github.com/pinepain/homebrew-devtools/master/Formula/v8@6.6.rb`
DOES work, (in case anyone else is just trying to get v8)

**Comment by thiphariel** [comment]
`homebrew/php` is flagged as deprecated. All formulas have been migrated in `homebrew/core` since the end of March 2018. That should be the issue :)

**Comment by SoylentGraham** [comment]
I kinda presumed the syntax could be correct, even if a dependency was missing. But then I'm not familiar with setting up taps so, I'm probably wrong :)

**Comment by thiphariel** [comment]
I'm also currently investing on install v8js on my Mac. I'm not quite familiar with brew too... I just know how to install / update / remove formulas, but don"t know how they really work ... 🤔

**Comment by SoylentGraham** [comment]
If you just need V8 (as I do, I need a version >5.1 which homebrew currently supports) you can just install that directly
`brew install https://raw.github.com/pinepain/homebrew-devtools/master/Formula/v8@6.6.rb`

**Comment by pinepain** [comment]
Hi! Thanks for reporting, I'll look into this (btw, PRs are welcomed).

**Comment by pinepain** [comment]
Hi, in #6 I decided to remove PHP formulae. Also, all v8-relate formulae will be moved to the phpv8/tap tap within next few weeks and it will be the new home. I'm stopping building homebrew-compatible binaries for v8 as it was previously done manually (v8 build times out on travis) and anyway, I'm not sure anybody was sticking to the exact v8 versions I used.
